source 'https://rubygems.org'

gem 'settingslogic'
gem 'activerecord', require: 'active_record'
gem 'zss-commons', git: 'git@github.com:dadah/zss-commons.git'
gem 'json', '~> 1.8.3', '>= 1.8.3.1'
gem 'zss', '0.0.3'

gem 'bigdecimal' 

gem 'pg', '0.18.2'
gem 'byebug', '11.1.3'
gem 'msgpack', '1.4.2'


group :development, :test do
  gem 'pry-byebug'
end

group :development do
  gem 'guard-rspec', require: false
end

group :test do
  gem 'sqlite3'
  gem 'rspec'
end